export * from './header/header.component';
export * from './header2/header2.component';
export * from './main/main.component';
export * from './footer/footer.component';
export * from './aside/aside.component';
export * from './aside2/aside2.component';
export * from './loaders/loader1.component'
export * from './maps/mapDriver1/map.component';
export * from './maps/mapDriver2/map.component';
export * from './maps/mapDriver3/map.component';
export * from './maps/mapUser1/map.component';
export * from './privateRoute/privateRoute.component';
export * from './alerts/component/alerts.component';
